#!/bin/bash
# Run only one instance per time. Restart when another instance found.
#
pid=$(ps x | grep -E '/usr/local/bin/adgui-(wayland|xlibre)$' | awk '{print $1}')
kill $pid 2>/dev/null

# Run binary for X11/XLibre by default.
binary=adgui-xlibre
if [[ -n "$WAYLAND_DISPLAY" || "$XDG_SESSION_TYPE" == "wayland" ]]; then
    # I guess Wayland session is active.
    binary=adgui-wayland
fi

/usr/local/bin/${binary} $@
# ^^^ optionally add for debug: >/tmp/adgui.log 2>&1
